image: node:10.18

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run-script build
    - echo $CI_JOB_ID > dist/CI_JOB_ID
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  stage: test
  image: alekzonder/puppeteer
  variables:
    HEADLESS: 'true'
  script:
    - cd tests
    - npm install
    - ./node_modules/codeceptjs/bin/codecept.js run --debug --steps
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - tests/output
pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv dist/* public
  artifacts:
    paths:
      - public
  only:
    - release
